### PR TITLE
Typescript rewrite

### PR DESCRIPTION
**Pull request by PeterKottas**
🎉 It's alive 🎉 

Highlights of this PR:

- Typescript rewrite done
- All tests working
- Prettier runs by reading tslint config.
- f12 navigates between projects properly
- Fixed a gazilion weird little nuances that had to do with types, typos or problems in code.
- This also fixes a lot of existing comments that were pointing to various issues. Most of these had something to do with es-link or flow types in general
- Changed tooling section in readme
- Added a Known issue in readme (sometimes vscode locks declaration files so you have to run build again)
- Removed all traces of flow and generally cleaned up the code
- Declarations are exported along with js files and js.maps. That means typescript people will love us.

Admittedly, this is probably biggest PR in the history of universe :D I rly tried to check everything to make your life simple. Hoping it will go as smooth as possible. Also I am here for any questions you might have.

### CODE REVIEW

**Comment by PeterKottas** [comment]
Nail biter waiting for those green checks to appear. Going to get myself a drink now 🍺

**Comment by aeneasr** [comment]
Oh shit, this is massive! There's no way for me to review it so I'll probably just check if and how it works locally and then merge. We might have to fix a couple of things as the next releases come rolling in.

**Comment by PeterKottas** [comment]
Yeah that's what I though. +51,913, −106,061, Files changed 289 says it all. I did extensive testing and all seems fine. But please, by all means, dig in ;)

Also I assumed this release will be 0.6.0 and wrote upgrade docs. No extensive and it can be change, just want to make sure I won't forget.

**Comment by aeneasr** [comment]
Sorry, pre-christmas was just insane. I'll try to get it done on on Saturday/Sunday

**Comment by PeterKottas** [comment]
Awesome mate! Thanks for info, I am here if you need any help with these.

**Comment by aeneasr** [comment]
Awesome! Looks like everything works perfectly

**Comment by PeterKottas** [comment]
Phew :)

**Pull request merged**
