### PR TITLE
Move to typescript (work in progress)

### PR DESCRIPTION
**Pull request by aeneasr**
This requires react-scripts to upgrade to babel >= 7.0.0-rc.1 because we need the babel typeform preset which is only compatible with later versions of babel 7.0.0-beta. Best idea is to wait for stable 7.0.0. Twitter says this will be this week?

### CODE REVIEW

**Comment by arekkas** [comment]
Yeah, 0.4.0 will land before that, no worries

**Comment by aeneasr** [comment]
This primarily depends on https://github.com/facebook/create-react-app/milestone/30

**Comment by PeterKottas** [comment]
Babel 7 is out 🎉

**Comment by aeneasr** [comment]
We will have to wait for: https://github.com/facebook/create-react-app/milestone/30

**Comment by aeneasr** [comment]
react-scripts 2.0 is out now. I don't have time to work on this for the time being but if I find a few free days I'll start doing that.

**Pull request closed without merging**
